[package]
name = "riscv_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bitfield = "0.14.0"
codespan-reporting = "0.11.1"
colored = "2.1.0"
itertools = "0.12.0"
rayon = "1.8.1"
term_size = "0.3.2"
