[package]
name = "rizz-v"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bitfield = "0.15.0"
codespan-reporting = "0.11.1"
colored = "2.1.0"
itertools = "0.12.1"
rayon = "1.10.0"
term_size = "1.0.0-beta1"
termion = "3.0.0"
